### ISSUE TITLE
Compiling with a lot of errors

### ISSUE THREAD

**Issue by SchneHa** [donschoof/TonuinoProgrammer#1]
I tried to compile your code but there are many errors because of missing declarations. Arduino IDE 1.8.19
`/Users/hasch/Documents/Arduino/TonuinoProgrammer2/TonuinoProgrammer2.ino: In function 'void loop()':
TonuinoProgrammer2:92:5: error: 'show_info' was not declared in this scope
     show_info();
     ^~~~~~~~~
TonuinoProgrammer2:96:5: error: 'show_help' was not declared in this scope
     show_help();
     ^~~~~~~~~
TonuinoProgrammer2:101:5: error: 'read_RFID' was not declared in this scope
     read_RFID();
     ^~~~~~~~~
TonuinoProgrammer2:109:5: error: 'write_RFID' was not declared in this scope
     write_RFID();
     ^~~~~~~~~~
TonuinoProgrammer2:122:5: error: 'write_RFID' was not declared in this scope
     write_RFID();
     ^~~~~~~~~~
TonuinoProgrammer2:136:5: error: 'write_RFID' was not declared in this scope
     write_RFID();
     ^~~~~~~~~~
TonuinoProgrammer2:152:7: error: 'write_RFID' was not declared in this scope
       write_RFID();
       ^~~~~~~~~~
TonuinoProgrammer2:167:5: error: 'write_RFID' was not declared in this scope
     write_RFID();
     ^~~~~~~~~~
TonuinoProgrammer2:181:5: error: 'write_RFID' was not declared in this scope
     write_RFID();
     ^~~~~~~~~~
TonuinoProgrammer2:195:5: error: 'write_RFID' was not declared in this scope
     write_RFID();
     ^~~~~~~~~~
TonuinoProgrammer2:208:7: error: 'write_RFID' was not declared in this scope
       write_RFID();
       ^~~~~~~~~~
TonuinoProgrammer2:212:18: error: a function-definition is not allowed here before '{' token
 void read_RFID() {
                  ^
TonuinoProgrammer2:352:19: error: a function-definition is not allowed here before '{' token
 void write_RFID() {
                   ^
TonuinoProgrammer2:428:35: error: a function-definition is not allowed here before '{' token
 void assigned_mode(byte buffer[]) {
                                   ^
TonuinoProgrammer2:540:18: error: a function-definition is not allowed here before '{' token
 void show_info() {
                  ^
TonuinoProgrammer2:556:18: error: a function-definition is not allowed here before '{' token
 void show_help() {
                  ^
TonuinoProgrammer2:577:18: error: a function-definition is not allowed here before '{' token
 void showError() {
                  ^
TonuinoProgrammer2:585:15: error: a function-definition is not allowed here before '{' token
 void showOK() {
               ^
TonuinoProgrammer2:598:20: error: a function-definition is not allowed here before '{' token
 void echoCommand() {
                    ^
TonuinoProgrammer2:614:41: error: a function-definition is not allowed here before '{' token
 bool checkTwo(uint8_t a[], uint8_t b[]) {
                                         ^
TonuinoProgrammer2:626:53: error: a function-definition is not allowed here before '{' token
 void dump_byte_array(byte* buffer, byte bufferSize) {
                                                     ^
TonuinoProgrammer2:633:25: error: a function-definition is not allowed here before '{' token
 bool waitForCardReady() {
                         ^
TonuinoProgrammer2:644:1: error: expected '}' at end of input
 }
 ^
exit status 1
'show_info' was not declared in this scope
`

**Comment by SchneHa** [comment]
OK, it's because of a missing "}" in line 211.
But it doesn't work, thus! In serial console only these lines appear:
`ausgeführt. Bitte lege jetzt deine Karte auf den Leser!

 wurde erfolgreich ausgeführt
 ausgeführt. Bitte lege jetzt deine Karte auf den Leser!
`
After that nothing happens presenting a card.

**Comment by donschoof** [comment]
Ok. I'll take a look at this. Which Board do you use?

**Comment by donschoof** [comment]
I've checked the project and the master compiles as it should for the Arduino Nano & the ESP32

**Comment by SchneHa** [comment]
You are right, for any reason the code I inserted was not complete! Now, I did a new copy/paste and it works. Thank you for pointing me to that.
